board_library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('deskovky/', views.DeskovkaListView.as_view(), name='deskovka_list'),
    path('zanry/', views.ZanrListView.as_view(), name='zanr_list'),
    path('rozsireni/', views.RozsireniListView.as_view(), name='rozsireni_list'),
    path('deskovka/<int:pk>/', views.DeskovkaDetailView.as_view(), name='deskovka_detail'),
    path('zanr/<int:pk>/', views.zanr_detail, name='zanr_detail'),
    path('rozsireni/<int:pk>/', views.rozsireni_detail, name='rozsireni_detail'),
    path('deskovka/add/', views.create_deskovka, name='deskovka_create'),
    path('zanr/add/', views.zanr_create, name='zanr_create'),
    path('rozsireni/add/', views.rozsireni_create, name='rozsireni_create'),
    path('deskovka/<int:pk>/edit/', views.upadate_deskovka, name='deskovka_update'),
    path('rozsireni/<int:pk>/edit/', views.rozsireni_update, name='rozsireni_update'),
    path('deskovka/<int:pk>/delete/', views.delete_deskovka, name='deskovka_delete'),
    path('zanr/<int:pk>/delete/', views.zanr_delete, name='zanr_delete'),
    path('rozsireni/<int:pk>/delete/', views.rozsireni_delete, name='rozsireni_delete'),
    path('tvurci/', views.tvurci_list, name='tvurci_list'),
    path('tvurci/add/', views.tvurci_create, name='tvurci_create'),
    path('tvurci/<int:pk>/', views.tvurci_detail, name='tvurci_detail'),
    path('tvurci/<int:pk>/edit/', views.tvurci_update, name='tvurci_update'),
    path('tvurci/<int:pk>/delete/', views.tvurci_delete, name='tvurci_delete'),
    path('vydavatelstvi/', views.vydavatelstvi_list, name='vydavatelstvi_list'),
    path('vydavatelstvi/<int:pk>/', views.vydavatelstvi_detail, name='vydavatelstvi_detail'),
    path('vydavatelstvi/add/', views.vydavatelstvi_create, name='vydavatelstvi_create'),
    path('vydavatelstvi/<int:pk>/edit/', views.vydavatelstvi_update, name='vydavatelstvi_update'),
    path('vydavatelstvi/<int:pk>/delete/', views.vydavatelstvi_delete, name='vydavatelstvi_delete'),
    path('deskovka/<int:hra_id>/hodnoceni/', views.add_change_review, name='hodnoceni_add'),
    path('deskovka/<int:hra_id>/hodnoceni/smazat/', views.review_delete, name='hodnoceni_delete'),
    path('deskovka/<int:hra_id>/hodnoceni/vse/', views.review_deskovky, name='hodnoceni_list'),









    

]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
# Create your models here.


class Deskovka(models.Model):
    nazev = models.CharField(max_length=80, verbose_name="Jméno deskové hry", help_text="Zadejte jméno deskové hry", default='',
            error_messages={'blank':'Jméno deskové hry musí být vyplněno'})
    alt = models.CharField(max_length=80, verbose_name="Alternativní jméno deskové hry", help_text="Zadejte alternativní jméno deskové hry",default='',blank=True, null=True,)
    zanry = models.ManyToManyField('Zanr',related_name='deskovky',verbose_name='Žánry deskové hry',help_text='Vyberte jeden nebo více žánrů',blank=True)
    designer = models.ManyToManyField('Tvurci', related_name='deskovky', verbose_name='Tvůrci deskové hry', help_text='Vyberte jednoho nebo více tvůrců', blank=True)
    vydavatelstvi = models.ManyToManyField('Vydavatelstvi', related_name='deskovky',verbose_name='Vydavatelství', help_text='Vyberte jméno vydavatelství deskové hry', blank=True)
    vydani = models.IntegerField(blank=True,null=True, verbose_name='Datum vydání')
    minvek = models.IntegerField(verbose_name='Minimální věk', help_text='Zadejte minimální věk', validators=[MinValueValidator(0), MaxValueValidator(99)],default=0)
    cas = models.IntegerField(verbose_name='Délka hry', help_text='Zadejte délku hry v minutách', validators=[MinValueValidator(0), MaxValueValidator(999)], default=0)
    min_hracu = models.IntegerField(verbose_name='Minimální počet hráčů', help_text='Zadejte minimální počet hráčů', validators=[MinValueValidator(1), MaxValueValidator(99)],default=1)
    max_hracu = models.IntegerField(verbose_name='Maximální počet hráčů', help_text='Zadejte maximální počet hráčů', validators=[MinValueValidator(1), MaxValueValidator(99)],default=1)
    KOMPLEXITA = [(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'), ]
    komplexita = models.PositiveIntegerField(choices=KOMPLEXITA, verbose_name="Komplexita hry", default=3)
    fotografie = models.ImageField(upload_to='deskovky',verbose_name='Fotografie',blank=True,null=True)
    popis = models.TextField(verbose_name='Popis', help_text='Zadejte popis deskové hry',blank=True, null=True)

    class Meta:
        verbose_name = 'Deskovka'
        verbose_name_plural = 'Deskovky'

    def __str__(self):
        return f'{self.nazev},{self.alt}'



class Zanr(models.Model):
    nazev = models.CharField(max_length=20, verbose_name='Název žánru', help_text='Zadejte název žánru')

    class Meta:
        ordering = ['nazev']
        verbose_name = 'Žánr'
        verbose_name_plural = 'Žánry'

    def __str__(self):
        return f'{self.nazev}'


class DeskovkaZanr(models.Model):
    deskovka = models.ForeignKey(Deskovka, on_delete=models.CASCADE, related_name='deskovka_zanr')
    zanr = models.ForeignKey(Zanr, on_delete=models.CASCADE, related_name='zanr_deskovka')

    class Meta:
        verbose_name = 'Žánr deskovky'
        verbose_name_plural = 'Žánry deskovek'

    def __str__(self):
        return f'{self.deskovka.nazev} - {self.zanr.nazev}'
    

class Rozsireni(models.Model):
    nazev = models.CharField(max_length=80, verbose_name='Název rozšíření', help_text='Zadejte název rozšíření')
    deskovka = models.ForeignKey(Deskovka, on_delete=models.CASCADE, related_name='rozsirena_deskovka')
    zanry = models.ManyToManyField('Zanr',related_name='rozsireni',verbose_name='Žánry deskové hry',help_text='Vyberte jeden nebo více žánrů',blank=True)
    designer = models.ManyToManyField('Tvurci', related_name='rozsireni', verbose_name='Tvůrci deskové hry', help_text='Vyberte jednoho nebo více tvůrců', blank=True)
    vydavatelstvi = models.ManyToManyField('Vydavatelstvi', related_name='rozsireni',verbose_name='Vydavatelství', help_text='Vyberte jméno vydavatelství deskové hry', blank=True)
    vydani = models.IntegerField(blank=True,null=True, verbose_name='Datum vydání')
    popis = models.TextField(verbose_name='Popis', help_text='Zadejte popis rozšíření')
    fotografie = models.ImageField(upload_to='rozsireni',verbose_name='Fotografie',blank=True,null=True)

    class Meta:
        verbose_name = 'Rozšíření'
        verbose_name_plural = 'Rozšíření'

    def __str__(self):
        return f'{self.nazev}'
    

class Vydavatelstvi(models.Model):
    Jmeno = models.CharField(max_length=80, verbose_name='Jméno vydavatelství', help_text='Zadejte jméno vydavatelství')

    class Meta:
        verbose_name = 'Vydavatelství'
        verbose_name_plural = 'Vydavatelství'

    def __str__(self):
        return f'{self.Jmeno}'

class DeskovkaVydavatelstvi(models.Model):
    deskovka = models.ForeignKey(Deskovka, on_delete=models.CASCADE, related_name='deskovka_vydavatelstvi')
    vydavatelstvi = models.ForeignKey(Vydavatelstvi, on_delete=models.CASCADE, related_name='vydavatelstvi_deskovka')

    class Meta:
        verbose_name = 'Vydavatelství deskovky'
        verbose_name_plural = 'Vydavatelství deskovek'

    def __str__(self):
        return f'{self.deskovka.nazev} - {self.vydavatelstvi.Jmeno}'



class Tvurci(models.Model):
    ROLE_CHOICES = [
        ('designer', 'Designer'),
        ('illustrator', 'Ilustrátor'),
    ]
    Jmeno = models.CharField(max_length=80, verbose_name='Jméno tvůrce', help_text='Zadejte jméno tvůrce')
    Prijmeni = models.CharField(max_length=80, verbose_name='Příjmení tvůrce', help_text='Zadejte příjmení tvůrce')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, verbose_name='Role',blank=True, null=True, help_text='Vyberte roli tvůrce')
    zivotopis = models.TextField(verbose_name='Životopis', help_text='Zadejte životopis tvůrce', blank=True, null=True)
    fotografie = models.ImageField(upload_to='tvurci', null=True, blank=True, verbose_name='Fotografie')

    class Meta:
        verbose_name = 'Tvůrce'
        verbose_name_plural = 'Tvůrci'

    def __str__(self):
        return f'{self.Jmeno} {self.Prijmeni} - ({self.get_role_display()})'
    

class DeskovkaTvurce(models.Model):
    deskovka = models.ForeignKey(Deskovka, on_delete=models.CASCADE, related_name='deskovka_tvurce')
    tvurce = models.ForeignKey(Tvurci, on_delete=models.CASCADE, related_name='tvurce_deskovka')

    class Meta:
        verbose_name = 'Tvůrce deskovky'
        verbose_name_plural = 'Tvůrci deskovek'

    def __str__(self):
        return f'{self.deskovka.nazev} - {self.tvurce.Jmeno} {self.tvurce.Prijmeni}'
    

class Hodnoceni(models.Model):
    Hra = models.ForeignKey('Deskovka', on_delete=models.CASCADE, related_name='hodnoceni_set')
    uzivatel = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hodnoceni')
    hodnoceni = models.IntegerField(verbose_name='Hodnocení', help_text='Zadejte hodnocení', validators=[MinValueValidator(0), MaxValueValidator(10)])
    datum = models.DateField(auto_now_add=True, verbose_name='Datum hodnocení')
    recenze = models.TextField(verbose_name='Recenze', help_text='Zadejte recenzi')

    class Meta:
        verbose_name = 'Hodnocení'
        verbose_name_plural = 'Hodnocení'

    def __str__(self):
        return f'{self.Hra.nazev} - {self.uzivatel.username} - {self.hodnoceni}'



library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Deskovka, Zanr, Rozsireni, Tvurci, Vydavatelstvi, Hodnoceni


class BoardModelForm(forms.ModelForm):
    class Meta:
        model = Deskovka
        fields = [ 'nazev', 'alt','designer', 'vydavatelstvi','zanry', 'vydani', 'minvek', 'cas',
            'min_hracu', 'max_hracu', 'komplexita', 'fotografie', 'popis']
        labels = {
            'nazev': 'Název hry',
            'alt': 'Alternativní název',
            'designer': 'Jméno tvůrce/ců',
            'vydavatelstvi': 'Název vydavatelství',
            'zanry': 'Žánr/y',
            'vydani': 'Rok vydání',
            'minvek': 'Minimální věk',
            'cas': 'Délka hry (min)',
            'min_hracu': 'Min. hráčů',
            'max_hracu': 'Max. hráčů',
            'komplexita': 'Komplexita',
            'fotografie': 'Obrázek',
            'popis': 'Popis hry',
        }
        help_texts = {
            'nazev': 'Zadejte jméno deskové hry',
            'alt': 'Zadejte alternativní jméno deskové hry',
            'designer': 'Vyberte jméno tvůrce/ců hry',
            'vydavatelstvi': 'Vyberte vydavatelství deskové hry',
            'zanry': 'Vyberte žánr či žánry deskové hry',
            'rok_vydani': 'Zadejte rok vydání deskové hry',
            'minimalni_vek': 'Zadejte minimální věk',
            'prum_cas': 'Zadejte průměrnou délku hry v minutách',
            'min_hracu': 'Zadejte minimální počet hráčů',
            'max_hracu': 'Zadejte maximální počet hráčů',
            'komplexita': 'Zadejte komplexitu hry (0-5)',
            'fotografie': 'Vyberte fotografii deskové hry',
            'popis': 'Zadejte popis deskové hry',
        }
        widgets = {
            'nazev': forms.TextInput(attrs={'class': 'form-control'}),
            'alt': forms.TextInput(attrs={'class': 'form-control'}),
            'designer' : forms.CheckboxSelectMultiple(),
            'zanry': forms.CheckboxSelectMultiple(),
            'vydavatelstvi': forms.CheckboxSelectMultiple(),
            'rok_vydani': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'minimalni_vek': forms.NumberInput(attrs={'class': 'form-control'}),
            'prum_cas': forms.NumberInput(attrs={'class': 'form-control'}),
            'min_hracu': forms.NumberInput(attrs={'class': 'form-control'}),
            'max_hracu': forms.NumberInput(attrs={'class': 'form-control'}),
            'komplexita': forms.Select(attrs={'class': 'form-control'}),
            'popis': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def clean_fotografie(self):
        fotografie = self.cleaned_data.get('fotografie')
        if fotografie:
            if not fotografie.name.endswith(('.jpg', '.jpeg', '.png')):
                raise forms.ValidationError('Fotografie musí být ve formátu JPG, JPEG nebo PNG.')
        return fotografie    
        
        
class ZanrForm(forms.ModelForm):
    class Meta:
        model = Zanr
        fields = ['nazev']

class RozsireniForm(forms.ModelForm):
    class Meta:
        model = Rozsireni
        fields = ['nazev', 'deskovka','designer', 'vydavatelstvi','zanry', 'vydani', 'popis', 'fotografie']
        labels = {
            'nazev': 'Název rozšíření',
            'deskovka': 'Deskova hra',
            'designer': 'Jméno tvůrce/ců',
            'vydavatelstvi': 'Název vydavatelství',
            'zanry': 'Žánr/y',
            'vydani': 'Datum vydání',
            'popis': 'Popis rozšíření',
            'fotografie': 'Obrázek rozšíření',
        }
        widgets = {
            'nazev': forms.TextInput(attrs={'class': 'form-control'}),
            'designer' : forms.CheckboxSelectMultiple(),
            'zanry': forms.CheckboxSelectMultiple(),
            'vydavatelstvi': forms.CheckboxSelectMultiple(),
            'vydani': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'popis': forms.Textarea(attrs={'class': 'form-control'}),

        }        
        def clean_fotografie(self):
            fotografie = self.cleaned_data.get('fotografie')
            if fotografie:
                if not fotografie.name.endswith(('.jpg', '.jpeg', '.png')):
                    raise forms.ValidationError('Fotografie musí být ve formátu JPG, JPEG nebo PNG.')
            return fotografie    

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'username', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class TvurciForm(forms.ModelForm):
    class Meta:
        model = Tvurci
        fields = ['Jmeno', 'Prijmeni', 'role', 'zivotopis', 'fotografie']
        labels = {
            'Jmeno': 'Jméno tvůrce',
            'Prijmeni': 'Příjmení tvůrce',
            'role': 'Role tvůrce',
            'zivotopis': 'Životopis',
            'fotografie': 'Fotografie',
        }
        widgets = {
            'Jmeno': forms.TextInput(attrs={'class': 'form-control'}),
            'Prijmeni': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'zivotopis': forms.Textarea(attrs={'class': 'form-control'}),
            'fotografie': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_fotografie(self):
        fotografie = self.cleaned_data.get('fotografie')
        if fotografie:
            ext = fotografie.name.lower().split('.')[-1]
            if ext not in ['jpg', 'jpeg', 'png']:
                raise forms.ValidationError('Fotografie musí být ve formátu JPG, JPEG nebo PNG.')
        return fotografie
    
class VydavatelstviForm(forms.ModelForm):
    class Meta:
        model = Vydavatelstvi
        fields = ['Jmeno']
        labels = {
            'Jmeno': 'Jméno vydavatelství',
        }
        widgets = {
            'Jmeno': forms.TextInput(attrs={'class': 'form-control'}),
        }   
class HodnoceniForm(forms.ModelForm):
    class Meta:
        model = Hodnoceni
        fields = ['hodnoceni', 'recenze']
        labels = {
            'hodnoceni': 'Hodnocení (0–10)',
            'recenze': 'Text recenze',
        }
        widgets = {
            'hodnoceni': forms.NumberInput(attrs={'min': 0, 'max': 10, 'class': 'form-control'}),
            'recenze': forms.Textarea(attrs={'rows': 4, 'class': 'form-control'}),
        }

    def clean_hodnoceni(self):
        hodnoceni = self.cleaned_data.get('hodnoceni')
        if hodnoceni is not None and (hodnoceni < 0 or hodnoceni > 10):
            raise forms.ValidationError("Hodnocení musí být mezi 0 a 10.")
        return hodnoceni        

library/templates/games/boardgames_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Přidat deskovou hru{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <h2 class="title is-3">Přidat novou deskovou hru</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="box">
        {% for field in form %}
          <div class="field">
            <label class="label">{{ field.label }}</label>
            <div class="control">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="help is-info">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
      </div>

      <div class="buttons">
        <button type="submit" class="button is-primary">Uložit</button>
        <a href="{% url 'deskovka_list' %}" class="button is-light">Zpět na seznam</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}

library/templates/games/boardgames_delete.html
{% extends 'base.html' %}
{% block title %}Smazat deskovou hru{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="notification is-danger">
      <h2 class="title is-4">Opravdu chcete smazat deskovou hru: <strong>"{{ deskovka.nazev }}"</strong>?</h2>

      <form method="post">
        {% csrf_token %}
        <div class="buttons mt-4">
          <button type="submit" class="button is-light">Ano, smazat</button>
          <a href="{% url 'deskovka_detail' deskovka.pk %}" class="button is-light">Ne, zpět</a>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock %}

library/templates/games/boardgames_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ deskovka.nazev }}{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    
    <div class="columns is-vcentered">
      <div class="column is-8">
        <h1 class="title">{{ deskovka.nazev }}</h1>
        {% if deskovka.alt %}
          <p class="subtitle">({{ deskovka.alt }})</p>
        {% endif %}
      </div>


    </div>

    <div class="columns">
      <div class="column is-one-third">
        {% if deskovka.fotografie %}
          <figure class="image is-4by3">
            <img src="{{ deskovka.fotografie.url }}" alt="{{ deskovka.nazev }}">
          </figure>
        {% else %}
          <figure class="image is-4by3">
            <img src="{% static 'images/placeholder.png' %}" alt="bez obrázku">
          </figure>
        {% endif %}
      </div>

      <div class="column">
        <p><strong>Rok vydání:</strong> {{ deskovka.vydani }}</p>
        <p><strong>Minimální věk:</strong> {{ deskovka.minvek }}</p>
        <p><strong>Délka hry:</strong> {{ deskovka.cas }} minut</p>
        <p><strong>Počet hráčů:</strong> {{ deskovka.min_hracu }}–{{ deskovka.max_hracu }}</p>
        <p><strong>Komplexita:</strong> {{ deskovka.get_komplexita_display }}</p>

        <p><strong>Žánry:</strong>
          {% for zanr in deskovka.zanry.all %}
            <span class="tag is-info">{{ zanr.nazev }}</span>
          {% endfor %}
        </p>

        <p><strong>Tvůrci:</strong>
          {% for tvurce in deskovka.designer.all %}
            <span class="tag is-warning">{{ tvurce.Jmeno }} {{ tvurce.Prijmeni }}</span>
          {% endfor %}
        </p>

        <p><strong>Vydavatelství:</strong>
          {% for vyd in deskovka.vydavatelstvi.all %}
            <span class="tag is-link">{{ vyd.Jmeno }}</span>
          {% endfor %}
        </p>

        <hr>
        <p>{{ deskovka.popis }}</p>
              {% if user.username == "admin" %}
        <div class="column is-4 has-text-right">
          <a href="{% url 'deskovka_update' deskovka.pk %}" class="button  is-info">Upravit</a>
          <a href="{% url 'deskovka_delete' deskovka.pk %}" class="button  is-danger">Smazat</a>
        </div>
      {% endif %}
      </div>
    </div>

    <hr>

    <div class="box">
      <h2 class="title is-5">Hodnocení</h2>

      {% for h in deskovka.hodnoceni_set.all %}
        <article class="message is-light">
          <div class="message-header">
            <p><strong>{{ h.uzivatel.username }}</strong> – {{ h.hodnoceni }}/10</p>
            {% if user == h.uzivatel %}
              <div>
                <a href="{% url 'hodnoceni_add' h.pk %}" class="button is-small is-info">Upravit</a>
                <a href="{% url 'hodnoceni_delete' h.pk %}" class="button is-small is-danger">Smazat</a>
              </div>
            {% endif %}
          </div>
          <div class="message-body">
            {{ h.recenze }}
          </div>
        </article>
      {% empty %}
        <p>Žádná hodnocení zatím nejsou.</p>
      {% endfor %}

      {% if user.is_authenticated %}
        <a href="{% url 'hodnoceni_add' deskovka.pk %}" class="button is-primary is-fullwidth mt-4">
          Přidat hodnocení
        </a>
      {% endif %}
    </div>

  </div>
</section>
{% endblock %}

library/templates/games/boardgames_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Seznam deskových her{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Seznam deskových her</h1>

    {% if deskovky %}
      <div class="columns is-multiline">
        {% for deskovka in deskovky %}
          <div class="column is-one-third">
            <div class="card">
              <div class="card-image">
                {% if deskovka.fotografie %}
                  <figure class="image is-4by3">
                    <a href="{% url 'deskovka_detail' deskovka.pk %}">
                    <img src="{{ deskovka.fotografie.url }}" alt="{{ deskovka.nazev }}">
                    </a>
                  </figure>
                {% else %}
                  <figure class="image is-4by3">
                    <a href="{% url 'deskovka_detail' deskovka.pk %}">
                    <img src="{% static 'images/placeholder.png' %}" alt="bez obrázku">
                    </a>
                    
                  </figure>
                {% endif %}
              </div>
              <div class="card-content">
                <p class="title is-5"><a href="{% url 'deskovka_detail' deskovka.pk %}">
                {{ deskovka.nazev }}
                </a></p>
                {% if deskovka.alt %}
                  <p class="subtitle is-6">({{ deskovka.alt }})</p>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>Žádné deskové hry nenalezeny.</p>
    {% endif %}

    {% if user.is_authenticated and user.username == "admin" %}
      <a class="button is-primary mt-4" href="{% url 'deskovka_create' %}">
        Přidat novou deskovku
      </a>
    {% endif %}
  </div>
</section>
{% endblock %}

library/templates/games/boardgames_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Přidat deskovou hru{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <h2 class="title is-3">Upravit deskovou hru</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="box">
        {% for field in form %}
          <div class="field">
            <label class="label">{{ field.label }}</label>
            <div class="control">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="help is-info">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
      </div>

      <div class="buttons">
        <button type="submit" class="button is-primary">Uložit</button>
        <a href="{% url 'deskovka_list' %}" class="button is-light">Zpět na seznam</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}